### ISSUE TITLE
Improve installation documentation

### ISSUE THREAD

**Issue by Thomas-lhuillier** [cycloidio/terracost#103]
It's not clear that you first need to clone the project and `cd` into it before running the `go get` mentioned [here](https://github.com/cycloidio/terracost/blob/master/README.md?plain=1#L14).

I wanted to install it, and after reading the docs, I simply copy-pasted the given command, and got the following error: 
```
$ go mod edit -replace github.com/hashicorp/terraform=github.com/cycloidio/terraform@v1.1.9-cy && go get github.com/cycloidio/terracost
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

Then I figured out I may need to clone the repo first and cd into it, which did the trick.

(Also, I know it's a bit the cherry on top of the cake, but providing a `brew` formula would be awesome for macOS users 😅)

**Comment by Thomas-lhuillier** [comment]
Closing as I realized it's a "pure" go package. Somehow I didn't realize that, for some reason I expected to be able to run it in the CLI (that said, it would make testing the library so much easier!)

**Comment by xescugc** [comment]
> (that said, it would make testing the library so much easier!)

Yes that's one of the thing I'm working on, to have a CLI to be able to use it directly if need be
