### ISSUE TITLE
Display Currency on the results

### ISSUE THREAD

**Issue by xescugc** [cycloidio/terracost#48]
We are storing the `currency` to the DB but it's not using it anywhere right now, from a caller PoV then the prices are just numbers without a reference.

For me this info is lost on the `cost.NewState` https://github.com/cycloidio/terracost/blob/master/cost/state.go#L68 as we are not setting the `currency` but the other values. Once it's inside of the `Component` I think it'll be dragged everywhere else.

**Comment by theskch** [comment]
Closed by PR #49
